# Default values for ca-user.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

job_type: chaincode_ops
nameOverride: "adminorg"
fullnameOverride: ""


imagePullSecrets: []
image:
  repository: 836713645333.dkr.ecr.us-east-2.amazonaws.com/hlf-builder
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.5"

ca:
 ica_endpoint: ica-adminorg.adminorg.svc:7051
 tlss_ca_endpoint: tls-ca.orderer.svc:7051
 k8s_tlss_ca_endpoint: tls-ca.orderer.svc:7051
 k8s_ca_endpoint: ica-adminorg.adminorg.svc:7051


orderer_endpoint: orderer0-orderer.orderer.svc:30000

hlf_domain: cvs-dev.net
k8s_hlf_domain: adminorg.svc
hlf_channel: "cvschannel"
fabric_actions:
  configure_org_channel: true

identities:
  - identity_name: admin
    identity_secret: adminSamplePassword
    identity_type: admin
  - identity_name: peer0-adminorg
    identity_secret: peer0adminorgSamplePassword
    identity_type: peer

# .Values.core_peer_mspconfigpath_override - Use only if your admin username is not "admin". 
# This must be under /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/
# Eg; /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/<admin-user>/msp
# core_peer_mspconfigpath_override: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/admin-adminorg/msp

# Organizations to be added
organizatons:
#  - name: provider
#    ica_endpoint: ica-provider.provider.svc:7051
#    ica_username: ica-provider
#    ica_secret: icaproviderSamplePassword
#    msp_dir: /crypto-config/peerOrganizations/msp
#    anchor_peer: peer0-provider.provider.svc
#    anchor_peer_port: 30000
 - name: receiver
   ica_endpoint: ica-receiver.receiver.svc:7051
   ica_username: ica-receiver
   ica_secret: icareceiverSamplePassword
   msp_dir: /crypto-config/peerOrganizations/msp
   anchor_peer: peer0-receiver.receiver.svc
   anchor_peer_port: 30000

csr_names_cn: IN
csr_names_st: Telangana
csr_names_l: Hyderabad
csr_names_o: vivvenns co

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
