apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-explore.fullname" . }}
  labels:
    {{- include "fabric-explore.labels" . | nindent 4 }}  
  #namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.explorer.containerPort }}   #check
    name: http
  selector:
    {{- include "fabric-explore.selectorLabels" . | nindent 4 }}
