{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- if .Values.storage.pvc_enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fabric-explore.fullname" . }}-db
  labels:
    {{- include "fabric-explore.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.storage.accessMode | default "ReadWriteOnce" }} 
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  storageClassName: {{ .Values.storage.storageClass | default "default" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fabric-explore.fullname" . }}-wallet
  labels:
    {{- include "fabric-explore.labels" $ | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.storage.accessMode | default "ReadWriteOnce" }} 
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  storageClassName: {{ .Values.storage.storageClass | default "default" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fabric-explore.fullname" . }}-certs
  labels:
    {{- include "fabric-explore.labels" $ | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.storage.accessMode | default "ReadWriteOnce" }} 
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  storageClassName: {{ .Values.storage.storageClass | default "default" }}

{{- end }}