{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- range .Values.orderers }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-{{ include "fabric-orderer.fullname" $ }}
  labels:
    {{- include "fabric-orderer.labels" $ | nindent 4 }}
  {{- with $.Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
