{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- $HlfDomain     := .Values.hlf_domain }}
{{- $IcaEndpoint   := .Values.ca.ica_endpoint }}
{{- $TlsCaEndpoint := .Values.ca.tlss_ca_endpoint | default .Values.ca.k8s_tlss_ca_endpoint }}
{{- $Msp_base_dir  := printf "%s%s" .Values.workdir "/peer/crypto/users" }}
{{- $k8s_HlfDomain := .Values.k8s_hlf_domain }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-tools.fullname" $ }}-fabric-ops
  labels:
    {{- include "fabric-tools.labels" $ | nindent 4 }}
data:
  config.yaml: |
      NodeOUs:
        Enable: true
        ClientOUIdentifier:
          Certificate: intermediatecerts/ca-cert.pem
          OrganizationalUnitIdentifier: client
        PeerOUIdentifier:
          Certificate: intermediatecerts/ca-cert.pem
          OrganizationalUnitIdentifier: peer
        AdminOUIdentifier:
          Certificate: intermediatecerts/ca-cert.pem
          OrganizationalUnitIdentifier: admin
        OrdererOUIdentifier:
          Certificate: intermediatecerts/ca-cert.pem
          OrganizationalUnitIdentifier: orderer
  enroll.sh: |
      enroll() {

      ica_url={{ $IcaEndpoint }}
      tlsca_url={{ $TlsCaEndpoint }}
      identity_name=$1
      identity_secret=$2
      identity_type=$3
      msp_base_dir=$4

      echo "Fetching public key cert of https://$ica_url"
      curl https://$ica_url/cainfo --insecure | jq .result.CAChain | base64 -i -d > /tmp/ca-cert.pem
      echo "Enrolling as user $identity_name to https://$ica_url"
        fabric-ca-client enroll -d \
            --url https://$identity_name:$identity_secret@$ica_url \
            --mspdir $msp_base_dir/$identity_name/msp \
            --tls.certfiles /tmp/ca-cert.pem \
            --csr.hosts $identity_name,$identity_name.{{ $HlfDomain }},$identity_name.{{ $k8s_HlfDomain }} \
            --csr.names O='{{ .Values.csr_names_o }}',L={{ .Values.csr_names_l }},ST={{ .Values.csr_names_st }},C={{ .Values.csr_names_cn }}
      echo "Re-arranging the MSP cert directory";
      cp $msp_base_dir/$identity_name/msp/intermediatecerts/* $msp_base_dir/$identity_name/msp/intermediatecerts/ca-cert.pem;
      cp /tmp/config.yaml $msp_base_dir/$identity_name/msp/config.yaml;
      sleep 5;

      if [ $identity_type = "admin" ]
        then 
        echo "No TLS enrollment is required for admin user tye, Skipping"
        else
        echo "Fetching public key cert of https://$tlsca_url"
        curl https://$tlsca_url/cainfo --insecure | jq .result.CAChain | base64 -i -d > /tmp/tlsca-cert.pem
        echo "Enrolling as user $identity_name to https://$tlsca_url"
          fabric-ca-client enroll -d \
              --url https://$identity_name:$identity_secret@$tlsca_url \
              --mspdir $msp_base_dir/$identity_name/tls \
              --tls.certfiles /tmp/tlsca-cert.pem \
              --csr.hosts $identity_name,$identity_name.{{ $HlfDomain }},$identity_name.{{ $k8s_HlfDomain }} \
              --enrollment.profile tls \
              --csr.names O='{{ .Values.csr_names_o }}',L={{ .Values.csr_names_l }},ST={{ .Values.csr_names_st }},C={{ .Values.csr_names_cn }}
        echo "Re-arranging the TLS cert directory";
        cp $msp_base_dir/$identity_name/tls/tlscacerts/* $msp_base_dir/$identity_name/tls/ca.crt;
        cp $msp_base_dir/$identity_name/tls/signcerts/* $msp_base_dir/$identity_name/tls/server.crt;
        cp $msp_base_dir/$identity_name/tls/keystore/* $msp_base_dir/$identity_name/tls/server.key;
        sleep 5;
      fi
      }
{{- range .Values.identities }}  
      enroll {{ .identity_name }} {{ .identity_secret }} {{ .identity_type }} {{ .msp_base_dir | default $Msp_base_dir }}
{{- end }}
      echo "Creating directory structure for Orderer"
      mkdir -p $ORDERER_BASE_PATH
      echo "Copying Orderer tls cert"
      cp /tmp/tlsca-cert.pem $ORDERER_BASE_PATH/ca-cert.pem